Fix typos
tlsfuzzer/python-ecdsa pull request #266
Opened 2021-10-22 15:38 UTC by kianmeng

2021-10-30 11:09 UTC, tomato42 commented on src/ecdsa/keys.py
> +        string) is endianness dependent! Signature computed over ``array.array``
```
$ flake8 setup.py speed.py src
src/ecdsa/keys.py:64:80: E501 line too long (80 > 79 characters)
```

2021-10-30 11:10 UTC, tomato42 requested changes
Looks good overall, thanks!
One nit though: it makes one line in the `keys.py` go over the limit, could you break that line?

2021-11-06 06:58 UTC, kianmeng commented
> Looks good overall, thanks! One nit though: it makes one line in the `keys.py` go over the limit, could you break that line?

@tomato42 Done. Please check again.

```
$ flake8 setup.py speed.py src
```

2021-11-06 15:12 UTC, merged

2021-11-06 15:12 UTC, tomato42 commented
Thank you!