Add CodeQL analysis
tlsfuzzer/python-ecdsa pull request #315
Opened 2023-02-24 21:48 UTC by tomato42

2023-02-28 14:10 UTC, jogme requested changes

2023-02-28 14:10 UTC, jogme commented on src/ecdsa/test_eddsa.py
> +        # verify that `__neq__` works as expected
typo; same below
```suggestion
        # verify that `__ne__` works as expected
```

2023-02-28 17:14 UTC, tomato42 commented on src/ecdsa/test_eddsa.py
> +        # verify that `__neq__` works as expected
fixed

2023-02-28 17:55 UTC, jogme approved these changes
looking good!

2023-02-28 19:22 UTC, merged

2023-02-28 19:23 UTC, tomato42 commented
@jogme Thanks!

2025-07-25 17:46 UTC, sajjantimalsina12 commented on src/ecdsa/test_eddsa.py
> +        # verify that `__neq__` works as expected
Working id 3833dd2f3e-3584f_
_update key <21c4d0a390a7fc27>
Give me new  code_______