remove usage of six.b("literal")
tlsfuzzer/python-ecdsa pull request #329
Opened 2024-01-06 00:43 UTC by a-detiste

as a side effect the program would maybe run faster

2024-01-06 13:02 UTC, tomato42 requested changes

2024-01-06 13:15 UTC, a-detiste commented on src/ecdsa/__init__.py
> -    six.b(""),
ok!

2024-01-06 14:02 UTC, a-detiste commented
I think `black` makes some code better, some code worse.

I don't like it personally.

BAD:

```
             y_qB=int(
-                "990C57520812BE512641E47034832106BC7D3E8DD0E4C7F1136D70065"
-                "47CEC6A",
+                "990C57520812BE512641E47034832106BC7D3E8DD0E4C7F1136D70065" "47CEC6A",
                 16,
             ),
             x_Z=int(
-                "89AFC39D41D3B327814B80940B042590F96556EC91E6AE7939BCE31F3A"
-                "18BF2B",
+                "89AFC39D41D3B327814B80940B042590F96556EC91E6AE7939BCE31F3A" "18BF2B",
                 16,
             ),
             y_Z=int(
-                "49C27868F4ECA2179BFD7D59B1E3BF34C1DBDE61AE12931648F43E5963"
-                "2504DE",
+                "49C27868F4ECA2179BFD7D59B1E3BF34C1DBDE61AE12931648F43E5963" "2504DE",
                 16,
             ),
```

GOOD:

```
-            x_Z=int(
-                "312DFD98783F9FB77B9704945A73BEB6DCCBE3B65D0F967DCAB574EB", 16
-            ),
-            y_Z=int(
-                "6F800811D64114B1C48C621AB3357CF93F496E4238696A2A012B3C98", 16
-            ),
+            dA=int("7C4B7A2C8A4BAD1FBB7D79CC0955DB7C6A4660CA64CC4778159B495E", 16),
+            x_qA=int("B104A67A6F6E85E14EC1825E1539E8ECDBBF584922367DD88C6BDCF2", 16),
+            y_qA=int("46D782E7FDB5F60CD8404301AC5949C58EDB26BC68BA07695B750A94", 16),
+            dB=int("63976D4AAE6CD0F6DD18DEFEF55D96569D0507C03E74D6486FFA28FB", 16),
         )
```

2024-01-06 14:03 UTC, a-detiste commented
(I had also fixed 2 duplicates of `sys` that pyflakes complained about)

2024-01-06 22:20 UTC, tomato42 commented
change those lines so that they're not two separate strings?

change from `...F1136D70065" "47CEC6A",` to `...F1136D7006547CEC6A",`?

2024-01-08 14:45 UTC, tomato42 commented
use `tox -e codeformat` to reformat according to project's black configuration, we don't use default black config

2024-01-08 20:33 UTC, tomato42 commented
Please [rebase](https://help.github.com/articles/about-git-rebase/) your PR on top of current master branch, then [force push](https://stackoverflow.com/a/10510482/462370) to the same branch as this PR is using.

Do not merge the `master` branch to this branch to update it.

2024-01-08 22:54 UTC, tomato42 approved these changes

2024-01-08 22:55 UTC, merged

2024-01-08 23:42 UTC, a-detiste commented
thank you